---
title: "Scrape real estate listings prices"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(rvest)
library(tidyverse)
library(httr)
library(glue)

knitr::opts_chunk$set(
  cache = F,
  echo = F,
  warning = F,
  message = F
)

```

# Scraping data from [listing.ca](https://listing.ca/mls)

```{r}
#' Scrape basic data from listing.ca
#'dim
#' @param url webpage URL to be scraped
#'
#' @return scraped webpage in HTML text
scraper <- function(url) {
  
  webpage <- read_html(url)
  
  tibble(
    # Address
    address = html_nodes(webpage, ".slt_address a") %>% 
      html_text(),
    
    # Number of bedrooms
    n_beds = html_nodes(webpage, ".slt_beds") %>% 
      html_text(),
    
    # Number of bathrooms
    n_baths = html_nodes(webpage, ".slt_baths") %>% 
      html_text(),
    
    # House pricesLO
    prices = html_nodes(webpage, ".slt_price") %>% 
      html_text()
  ) 
}

# General URL structure https://listing.ca/mls/?.cy.........422..$

# Condos listings https://listing.ca/mls/?1..........350..$
# Condo townhomes listings https://listing.ca/mls/?3..........3..$
# Townhomes listings https://listing.ca/mls/?2..........3..$
# Detached listings https://listing.ca/mls/?5..........3..$

condos_pages <- 1:300
condos_urls <- glue("https://listing.ca/mls/?1..........{condos_pages}..$")
condos_listings <- condos_urls %>% 
  map(.f = scraper) %>% 
  bind_rows() %>% 
  mutate(listing_type = "condo")


detached_pages <- 1:300
detached_urls <- glue("https://listing.ca/mls/?5..........{detached_pages}..$")
detached_listings <- detached_urls %>% 
  map(.f = scraper) %>% 
  bind_rows() %>% 
  mutate(listing_type = "detached")


townhomes_pages <- 1:50
townhomes_urls <- glue("https://listing.ca/mls/?2..........{townhomes_pages}..$")
townhomes_listings <- townhomes_urls %>% 
  map(.f = scraper) %>% 
  bind_rows() %>% 
  mutate(listing_type = "townhome")


condo_townhomes_pages <- 1:50
condo_townhomes_urls <- glue("https://listing.ca/mls/?3..........{condo_townhomes_pages}..$")
condo_townhomes_listings <- condo_townhomes_urls %>% 
  map(.f = scraper) %>% 
  bind_rows() %>% 
  mutate(listing_type = "condo_townhome")

all_listings <- condos_listings %>% 
  bind_rows(detached_listings) %>% 
  bind_rows(townhomes_listings) %>% 
  bind_rows(condo_townhomes_listings) %>% 
  # Clean numeric variable
  mutate(
    n_beds = str_replace_all(n_beds, "[^0-9+]", ""),
    n_baths = str_replace_all(n_baths, "[^0-9+]", ""),
    prices = str_replace_all(prices, "[^0-9]", "") %>% 
      as.numeric
  )


```

```{r}
#' Get postal code and other geocode data using geocoder API
#'
#' @param address 
#' @param city 
#' @importFrom jsonlite content fromJSON
#' @importFrom httr GET content
#'
#' @return JSON response object from Google Maps Geocoding API
get_geocode_data <- function(address){
  
  # Replace spaces with %20 for API URL
  address <- str_replace_all(address, " ", "+")
  
  # Get Google Cloud API Key
  API_KEY <- Sys.getenv("GCLOUD_API_KEY")
  
  # Fetch response from API
  res <- httr::GET(url = glue::glue(
    "https://maps.googleapis.com/maps/api/geocode/json?address={address},+ON,+Canada&key={API_KEY}"
  ))
  
  content <- httr::content(res, as = "text") %>% 
    jsonlite::fromJSON()
  
  return(content)
}

tictoc::tic()
listings_data <- all_listings %>% 
  mutate(geocode_res = map(address,
                           get_geocode_data))
tictoc::toc()

parse_response <- function(geocode_res,
                           data_element) {
  
  tryCatch(
    {
      res <- switch(
        data_element,
        "street_number" = geocode_res$results$address_components[[1]] %>% 
          dplyr::filter(grepl("street_number", types)) %>% 
          dplyr::pull(long_name),
        
        "route" = geocode_res$results$address_components[[1]] %>% 
          dplyr::filter(grepl("route", types)) %>% 
          dplyr::pull(long_name),
        
        "postal_code" = geocode_res$results$address_components[[1]] %>% 
          dplyr::filter(grepl("postal_code", types)) %>% 
          dplyr::pull(long_name),
        
        "sublocality" = geocode_res$results$address_components[[1]] %>% 
          dplyr::filter(grepl("sublocality", types)) %>%
          dplyr::pull(long_name),
        
        "locality" = geocode_res$results$address_components[[1]] %>% 
          dplyr::filter(grepl("\\blocality\\b", types)) %>% 
          dplyr::pull(long_name),
        
        "formatted_address" = geocode_res$results$formatted_address[1],
        
        "longitude" = geocode_res$results$geometry$location %>% 
          dplyr::pull(lat) %>%
          mean,
        
        "latitude" = geocode_res$results$geometry$location %>% 
          dplyr::pull(lng) %>% 
          mean
      )
      
      if (length(res)  == 0) {
        stop("data element missing")
      }
      
      return(res)
      
    }, error = function(e){
      return(NA_character_)
    }
  )
}


parsed_dataset <- listings_data %>%
  mutate(
    street_number = purrr::map_chr(geocode_res,
                                   .f = ~ parse_response(geocode_res = .,
                                                         data_element = "street_number")),
    
    route = purrr::map_chr(geocode_res,
                           .f = ~ parse_response(geocode_res = .,
                                                 data_element = "route")),
    
    # postal_code = purrr::map_chr(geocode_res,
    #                              .f = ~ parse_response(geocode_res = .,
    #                                                    data_element = "postal_code")),
    
    # sublocality = purrr::map_chr(geocode_res,
    #                              .f = ~ .$results$address_components[[1]] %>% 
    #                                dplyr::filter(grepl("sublocality", types)) %>% 
    #                                dplyr::pull(long_name)),
    
    locality = purrr::map_chr(geocode_res,
                              .f = ~ parse_response(geocode_res = .,
                                                    data_element = "locality")),
    
    formatted_address = purrr::map_chr(geocode_res,
                                       .f = ~ parse_response(geocode_res = .,
                                                             data_element = "formatted_address")),
    
    latitude = purrr::map_chr(geocode_res,
                              .f = ~ parse_response(geocode_res = .,
                                                    data_element = "longitude")),
    
    longitude = purrr::map_chr(geocode_res,
                               .f = ~ parse_response(geocode_res = .,
                                                     data_element = "latitude"))
    
  )

# Filter out incorrectly queried data
ontario_listings <- parsed_dataset %>% 
  filter(str_detect(formatted_address, "Canada")) %>% 
  mutate(
    postal_code = purrr::map_chr(geocode_res,
                                 .f = ~ parse_response(geocode_res = .,
                                                       data_element = "postal_code"))
  )

saveRDS(ontario_listings,
        file = "housing_data.rds",
        version = 3)

```



